# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
-   repo: local
    hooks:
        -   id: fmt
            name: Format sources
            entry: bash -c "cargo +nightly fmt --"
            language: system
            pass_filenames: false
        -   id: clippy
            name: Lint sources
            entry: bash -c "cargo +nightly clippy -- -D warnings"
            language: system
            pass_filenames: false
        -   id: udeps
            name: Find unused dependencies
            entry: bash -c "cargo +nightly udeps --all-targets "
            language: system
            pass_filenames: false
