[profile.dev]
panic = "unwind"
debug-assertions = false

[profile.release]
panic = "unwind"
debug-assertions = false
opt-level = 3

[workspace]
    members = [
        "main",
        "queue",
        "interop"
    ]
