version: '3.8'

services:

  crusty:
    container_name: crusty
    build:
      context: .
      dockerfile: ./infra/crusty/Dockerfile
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRUSTY_SEEDS=${CRUSTY_SEEDS:-}

  redis:
    container_name: crusty-redis
    build:
      context: ./infra/redis
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - redis-volume:/data
      - /etc/localtime:/etc/localtime:ro

  clickhouse:
    container_name: crusty-clickhouse
    build:
      context: ./infra/clickhouse
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - /etc/localtime:/etc/localtime:ro

  grafana:
    container_name: crusty-grafana
    restart: on-failure
    build:
      context: ./infra/grafana
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - grafana-volume:/var/lib/grafana
      - grafana-plugins:/grafana-plugins
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource 2.3.1
      - GF_PLUGIN_DIR=/grafana-plugins

volumes:
  redis-volume:
  clickhouse-volume:
  grafana-volume:
  grafana-plugins:
