version: '3.8'

services:

  crusty:
    container_name: crusty
    build:
      context: .
      dockerfile: ./infra/crusty/Dockerfile
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRUSTY_SEEDS=${CRUSTY_SEEDS:-}

  redis-queue:
    container_name: crusty-redis-queue
    build:
      context: ./infra/redis
    networks:
      crusty:
        ipv4_address: 172.16.2.1
    expose:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - redis-queue-volume:/data
      - /etc/localtime:/etc/localtime:ro

  redis-queue-2:
    container_name: crusty-redis-queue-2
    build:
      context: ./infra/redis
    networks:
      crusty:
        ipv4_address: 172.16.2.2
    expose:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - redis-queue-volume-2:/data
      - /etc/localtime:/etc/localtime:ro

  redis-calc:
    container_name: crusty-redis-calc
    build:
      context: ./infra/redis
    networks:
      crusty:
        ipv4_address: 172.16.3.1
    expose:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - redis-calc-volume:/data
      - /etc/localtime:/etc/localtime:ro

  clickhouse:
    container_name: crusty-clickhouse
    build:
      context: ./infra/clickhouse
    networks:
      crusty:
        ipv4_address: 172.16.1.1
    ports:
      - "0.0.0.0:8123:8123/tcp"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - /etc/localtime:/etc/localtime:ro

  grafana:
    container_name: crusty-grafana
    restart: on-failure
    build:
      context: ./infra/grafana
    networks:
      crusty:
        ipv4_address: 172.16.1.2
    links:
      - clickhouse
    ports:
      - "0.0.0.0:3000:3000/tcp"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - grafana-volume:/var/lib/grafana
      - grafana-plugins:/grafana-plugins
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource 2.3.1
      - GF_PLUGIN_DIR=/grafana-plugins

  unbound:
    container_name: crusty-unbound
    restart: on-failure
    build:
      context: ./infra/unbound
    networks:
      crusty:
        ipv4_address: 172.16.0.254
    expose:
      - "53"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./infra/unbound/conf:/opt/unbound/etc/unbound
      - /etc/localtime:/etc/localtime:ro

networks:
  crusty:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.0.0/16"

volumes:
  redis-queue-volume:
  redis-queue-volume-2:
  redis-calc-volume:
  clickhouse-volume:
  grafana-volume:
  grafana-plugins:
  unbound-volume:
