{
 "title": "Crusty",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": "crawler-1" },
   { "name": "DB", "query": "crusty" }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    sum(read_size_b) as \"RX Total\",\r\n    sum(write_size_b) as \"TX Total\"\r\nFROM $DB.metrics_task\r\n\r\nWHERE\r\n    $timeFilterByColumn(created_at)\r\n    $conditionalTest(AND host = '$host', $host)",
     "rawQuery": "SELECT\r\n    sum(read_size_b) as \"RX Total\",\r\n    sum(write_size_b) as \"TX Total\"\r\nFROM crusty.metrics_task\r\n\r\nWHERE\r\n    created_at >= toDateTime(1624482277) AND created_at <= toDateTime(1624482579)\r\n     AND host = 'crawler-1' ",
     "round": "0s"
    }
   ]
  },
  {
   "title": "General distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"OK\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND error=0  AND term = 0",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"OK\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481674) AND created_at <= toDateTime(1624481976)  AND host = 'crawler-1' \n    AND error=0  AND term = 0",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Error\"\r\n\r\nFROM $DB.metrics_task\r\n\r\nWHERE\r\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\r\n    AND error = 1",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Error\"\r\n\r\nFROM crusty.metrics_task\r\n\r\nWHERE\r\n    created_at >= toDateTime(1624481674) AND created_at <= toDateTime(1624481976)  AND host = 'crawler-1' \r\n    AND error = 1",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Term\"\r\n\r\nFROM $DB.metrics_task\r\n\r\nWHERE\r\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\r\n    AND term = 1",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Term\"\r\n\r\nFROM crusty.metrics_task\r\n\r\nWHERE\r\n    created_at >= toDateTime(1624481674) AND created_at <= toDateTime(1624481976)  AND host = 'crawler-1' \r\n    AND term = 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Term counts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Term by error\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND term=1 AND term_reason  = '' AND term_kind = 'Error'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Term by error\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481492) AND created_at <= toDateTime(1624481794)  AND host = 'crawler-1' \n    AND term=1 AND term_reason  = '' AND term_kind = 'Error'",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Term by panic\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND term=1 AND term_reason  = '' AND term_kind = 'Panic'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Term by panic\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481492) AND created_at <= toDateTime(1624481794)  AND host = 'crawler-1' \n    AND term=1 AND term_reason  = '' AND term_kind = 'Panic'",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Content Type\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND term=1 AND term_reason  = 'ContentType'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Content Type\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481492) AND created_at <= toDateTime(1624481794)  AND host = 'crawler-1' \n    AND term=1 AND term_reason  = 'ContentType'",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Redirect\"\r\n\r\nFROM $DB.metrics_task\r\n\r\nWHERE\r\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\r\n    AND term=1 AND term_reason  = 'Redirect'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Redirect\"\r\n\r\nFROM crusty.metrics_task\r\n\r\nWHERE\r\n    created_at >= toDateTime(1624481492) AND created_at <= toDateTime(1624481794)  AND host = 'crawler-1' \r\n    AND term=1 AND term_reason  = 'Redirect'",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Max Redirect\"\r\n\r\nFROM $DB.metrics_task\r\n\r\nWHERE\r\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\r\n    AND term=1 AND term_reason  = 'MaxRedirect'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Max Redirect\"\r\n\r\nFROM crusty.metrics_task\r\n\r\nWHERE\r\n    created_at >= toDateTime(1624481492) AND created_at <= toDateTime(1624481794)  AND host = 'crawler-1' \r\n    AND term=1 AND term_reason  = 'MaxRedirect'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Error counts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Other Errors\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND error=1 AND error_known  = ''",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Other Errors\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481901) AND created_at <= toDateTime(1624482203)  AND host = 'crawler-1' \n    AND error=1 AND error_known  = ''",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Status Timeout\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND error=1 AND error_known  = 'StatusTimeout'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Status Timeout\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481901) AND created_at <= toDateTime(1624482203)  AND host = 'crawler-1' \n    AND error=1 AND error_known  = 'StatusTimeout'",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 'total' as p, count(created_at) as \"Load Timeout\"\n\nFROM $DB.metrics_task\n\nWHERE\n    $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n    AND error=1 AND error_known  = 'LoadTimeout'",
     "rawQuery": "SELECT 'total' as p, count(created_at) as \"Load Timeout\"\n\nFROM crusty.metrics_task\n\nWHERE\n    created_at >= toDateTime(1624481901) AND created_at <= toDateTime(1624482203)  AND host = 'crawler-1' \n    AND error=1 AND error_known  = 'LoadTimeout'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Parsing time / 1mb of raw HTML Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    max(toUnixTimestamp(created_at) * 1000) as time,\n    sum(parse_time_micro) / sum(if(follow_ok = 1, read_size_b, 0)) / greatest($interval, 3) * 1024 * 1024 as \"Parsing time\"\nFROM $DB.metrics_task\n\nWHERE $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n\nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    max(toUnixTimestamp(created_at) * 1000) as time,\n    sum(parse_time_micro) / sum(if(follow_ok = 1, read_size_b, 0)) / greatest(1, 3) * 1024 * 1024 as \"Parsing time\"\nFROM crusty.metrics_task\n\nWHERE created_at >= toDateTime(1624484008) AND created_at <= toDateTime(1624484310)  AND host = 'crawler-1' \n\nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Job Queue Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest($interval, 3) as Enqueued\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'insert'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest(1, 3) as Enqueued\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473090) AND created_at <= toDateTime(1624473392)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'insert'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest($interval, 3) as Finished\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'update'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest(1, 3) as Finished\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473090) AND created_at <= toDateTime(1624473392)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'update'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest($interval, 3) as Dequeued\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'read'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time",
     "rawQuery": "SELECT\n    toUnixTimestamp(max(created_at))*1000 as time,\n    sum(items) / greatest(1, 3) as Dequeued\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473090) AND created_at <= toDateTime(1624473392)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'read'\n    \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    max(toUnixTimestamp(created_at)*1000) as time,\n    sum(read_size_b) / greatest($interval, 3) as RX,\n    sum(write_size_b) / greatest($interval, 3) as TX\nFROM $DB.metrics_task\n\nWHERE $timeFilterByColumn(created_at) $conditionalTest(AND host = '$host', $host)\nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    max(toUnixTimestamp(created_at)*1000) as time,\n    sum(read_size_b) / greatest(1, 3) as RX,\n    sum(write_size_b) / greatest(1, 3) as TX\nFROM crusty.metrics_task\n\nWHERE created_at >= toDateTime(1624483876) AND created_at <= toDateTime(1624484178)  AND host = 'crawler-1' \nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Job Queue Latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Enqueue\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'insert' \n    \nORDER BY time\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Enqueue\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473099) AND created_at <= toDateTime(1624473401)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'insert' \n    \nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Finish\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'update' \n    \nORDER BY time\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Finish\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473099) AND created_at <= toDateTime(1624473401)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'update' \n    \nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Dequeue\nFROM $DB.metrics_db\n\nWHERE\n    $timeFilterByColumn(created_at)\n    $conditionalTest(AND host = '$host', $host)\n    AND table_name = 'domains' AND label = 'read' \n    \nORDER BY time\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(created_at)*1000 as time,\n    took_ms as Dequeue\nFROM crusty.metrics_db\n\nWHERE\n    created_at >= toDateTime(1624473099) AND created_at <= toDateTime(1624473401)\n     AND host = 'crawler-1' \n    AND table_name = 'domains' AND label = 'read' \n    \nORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Pages/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    max(toUnixTimestamp(created_at) * 1000) as time,\n    count(follow_ok) / greatest($interval, 3) as Ok,\n    sum(term) / greatest($interval, 3) as Term,\n    sum(error) / greatest($interval, 3) as Error\nFROM $DB.metrics_task\n\nWHERE $timeFilterByColumn(created_at) $conditionalTest( AND host = '$host', $host)\n\nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest($interval, 3))\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    max(toUnixTimestamp(created_at) * 1000) as time,\n    count(follow_ok) / greatest(1, 3) as Ok,\n    sum(term) / greatest(1, 3) as Term,\n    sum(error) / greatest(1, 3) as Error\nFROM crusty.metrics_task\n\nWHERE created_at >= toDateTime(1624483833) AND created_at <= toDateTime(1624484135)  AND host = 'crawler-1' \n\nGROUP BY intDiv(toRelativeSecondNum(created_at), greatest(1, 3))\n\nORDER BY time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest($interval, 3) as JobUpdate\r\nFROM $DB.metrics_queue\r\n\r\nWHERE\r\n    $timeFilterByColumn(updated_at)\r\n    $conditionalTest(AND host = '$host', $host)\r\n    AND name = 'job_state_update'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest($interval, 3))\r\n    \r\nORDER BY time\r\n",
     "rawQuery": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest(1, 3) as JobUpdate\r\nFROM crusty.metrics_queue\r\n\r\nWHERE\r\n    updated_at >= toDateTime(1624473123) AND updated_at <= toDateTime(1624473425)\r\n     AND host = 'crawler-1' \r\n    AND name = 'job_state_update'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest(1, 3))\r\n    \r\nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest($interval, 3) as Job\r\nFROM $DB.metrics_queue\r\n\r\nWHERE\r\n    $timeFilterByColumn(updated_at)\r\n    $conditionalTest(AND host = '$host', $host)\r\n    AND name = 'job'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest($interval, 3))\r\n    \r\nORDER BY time\r\n",
     "rawQuery": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest(1, 3) as Job\r\nFROM crusty.metrics_queue\r\n\r\nWHERE\r\n    updated_at >= toDateTime(1624473123) AND updated_at <= toDateTime(1624473425)\r\n     AND host = 'crawler-1' \r\n    AND name = 'job'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest(1, 3))\r\n    \r\nORDER BY time",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest($interval, 3) as Parse\r\nFROM $DB.metrics_queue\r\n\r\nWHERE\r\n    $timeFilterByColumn(updated_at)\r\n    $conditionalTest(AND host = '$host', $host)\r\n    AND name = 'parser'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest($interval, 3))\r\n    \r\nORDER BY time\r\n",
     "rawQuery": "SELECT\r\n    toUnixTimestamp(max(updated_at))*1000 as time,\r\n    sum(len) / greatest(1, 3) as Parse\r\nFROM crusty.metrics_queue\r\n\r\nWHERE\r\n    updated_at >= toDateTime(1624473123) AND updated_at <= toDateTime(1624473425)\r\n     AND host = 'crawler-1' \r\n    AND name = 'parser'\r\n    \r\nGROUP BY intDiv(toRelativeSecondNum(updated_at), greatest(1, 3))\r\n    \r\nORDER BY time",
     "round": "0s"
    }
   ]
  }
 ]
}