datasources:
  - name: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://localhost:8123
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
