apiVersion: 1

datasources:
  - name: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
  - name: redis-calc
    type: redis-datasource
    access: proxy
    url: redis://redis-calc:6379
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
